chore: Enhance pairing test
hiero-ledger/hiero-cryptography pull request #138
Opened 2024-11-18 10:51 UTC by timo0

Fix https://github.com/hashgraph/hedera-services/issues/16302

2024-11-18 15:12 UTC, lpetrovic05 commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128BilinearPairingTest.java
> +    private void testBilinearityProperties(FieldElement a, FieldElement b, GroupElement P, GroupElement Q) {
final

2024-11-18 15:14 UTC, lpetrovic05 commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128FieldTest.java
> +        var largeValue = BigInteger.valueOf(Long.MAX_VALUE).add(BigInteger.valueOf(1000));
this is not very large, since field elements are 254 bit numbers

2024-11-18 15:16 UTC, lpetrovic05 commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128Test.java
> +        rng.nextBytes(msg);
this would ideally be a single call in the SeededRandom

2024-11-19 16:22 UTC, mxtartaglia-sl commented
@timo0 , like in hedera-services, let's use conventional commits https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13 names in the PRs.

@rbarkerSL @andrewb1269hg, guys, should something fail if we don't?

2024-11-19 17:20 UTC, mxtartaglia-sl requested changes
Timo, there are repeated tests, and some tests seem incomplete or have a wrong comments on top of the asserts.

When we were defining test cases you had the idea of generating points and results with an external library and using those results to validate in Java tests, I don't see any test of that sort and they would be useful.

Also, to match what we've been doing, please add final on all local variables.

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128BilinearPairingTest.java
> +        GroupElement Q = g2.generator();
Although it is a valuable test; it is incomplete as an edge scenarios input.

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128BilinearPairingTest.java
> +        assertNotNull(pairing, "Pairing of generators should not be null!");
Missing match check. Please validate externally and add the check. Also it would be helpful to include a link or reference to the tool used to check the billeality is correct.

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128GroupElementTest.java
> +        // Further checks as needed, possibly involving expected byte sequences.
Incomplete test? or wrong test name?

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128FieldTest.java
> +    void fieldElementAdditionCommutativity(final Random rng) {
this test is repeated

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128FieldTest.java
> +    void fieldElementMultiplicationDistributivity(final Random rng) {
same test is repeated in fieldEleemnts test

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128FieldTest.java
> +    void fieldElementAdditionAssociativity(final Random rng) {
repeated

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128FieldTest.java
> +    void fieldElementMultiplicationCommutativity(final Random rng) {
repeated in field element tests

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128FieldTest.java
> +    void fieldElementMultiplicationAssociativity(final Random rng) {
repeated

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128FieldTest.java
>  }
Besides repeating many tests, it seems that they belong to FieldElements test instead.

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128GroupElementTest.java
> +        var largeScalar = field.fromLong(Long.MAX_VALUE); // Using maximum possible scalar value
not maximum scalar value

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128GroupElementTest.java
> +        // Perform multiplication with the large scalar and check result (e.g., does not throw, is consistent)
Incomplete? or unnecessary comment?

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128GroupElementTest.java
> +        // Check that the point is valid (e.g., within the curve bounds if applicable)
The code could benefit from extra checks.
There is an exception we throw if the point is not on the curve

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128GroupTest.java
> +        assertEquals(element1, element2); // Consistent mapping of input to output
Why is element1 and element2 expected to be different?
I mean I could see the point of sending a different byte array with the same content but calling the method twice on the same input when there is no random source; it just seems to be checking Java determinism.

2024-11-19 17:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128GroupElementTest.java
> +        assertEquals(G1.add(G2).add(G3), G1.add(G2.add(G3)));
Maybe multiply by random scalars instead

2024-11-19 20:47 UTC, andrewb1269 commented
> @timo0 , like in hedera-services, let's use conventional commits https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13 names in the PRs.
> 
> @rbarkerSL @andrewb1269hg, guys, should something fail if we don't?

Good question. I'd think this is a larger tooling discussion. I know we've used `ci: ` at the beginning of commits, which is not called out in the conventional commits link you have.

Currently I lean towards putting a link in the new employee startup guide, but I don't know if it makes sense to invest tooling time in implementing and enforcing those standards.

@rbarkerSL thoughts?

2024-11-27 16:18 UTC, timo0 commented on cryptography/hedera-cryptography-altbn128/src/test/java/com/hedera/cryptography/altbn128/AltBn128Test.java
> +        rng.nextBytes(msg);
Currently we inject `Random` not `SeededRandom` maybe we create an issue to change this?

2024-11-27 16:33 UTC, mxtartaglia-sl submitted a review, later dismissed

2024-11-28 13:39 UTC, mxtartaglia-sl approved these changes

2024-11-28 14:05 UTC, merged

2025-01-14 17:47 UTC, swirlds-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/hedera-cryptography/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: