ci: add initial ci pipeline and gradle implementations
hiero-ledger/hiero-cryptography pull request #19
Opened 2024-07-17 15:34 UTC by rbarker-dev

**Description**:

Adds initial CI/CD pipelines for hedera-cryptography repository

**Related issue(s)**:

Fixes #12

2024-07-22 14:09 UTC, nathanklick requested changes
Maven Group ID should be `com.hedera.cryptography` and not `com.hedera` and the package/module prefix should be `com.hedera.cryptography`

2024-07-23 16:09 UTC, jjohannes approved these changes
@rbarkerSL and I worked on most of this together. :+1: from me.

Note for future reference: We copied `gradle/plugins` with only little adjustments from https://github.com/hashgraph/hedera-services. There might be configuration in there not needed in this project. This will be consolidated as part of https://github.com/hashgraph/hedera-services/issues/14255.

2024-07-23 16:43 UTC, mxtartaglia-sl reviewed
Adding some comments and questions.

2024-07-23 16:43 UTC, mxtartaglia-sl commented on .github/CODEOWNERS
> +###################################
Can we include platform-team as the owner of each of the modules?

2024-07-23 16:43 UTC, mxtartaglia-sl commented on build.gradle.kts
> +/*
Why would we want to keep this commented code? maybe remove it if not necessary?

2024-07-23 16:43 UTC, mxtartaglia-sl commented on hedera-cryptography-altbn128/build.gradle.kts
> +    id("com.hedera.gradle.services")
What are the implications of publishing with "com.hedera.gradle.services"?
As this is all to be maintained by the platform team, and to be used by the platform code

2024-07-23 16:43 UTC, mxtartaglia-sl commented on hedera-nativesupport/build.gradle.kts
> +    id("com.hedera.gradle.services")
In this case it seems that the group will be `com.hedera`
@nathanklick suggested `com.hedera.commons` for this module

2024-07-23 16:43 UTC, mxtartaglia-sl commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.services-publish.gradle.kts
> +                    organizationUrl = "https://www.hedera.com"
I see this is the plugin being used by pairings, pairings impl, native support, etc:

What about changing the name of this plugin to avoid confusion with the one in hedera-services and the distinction between `services` and `platform` code there?

Also, I don't see the smart contacts or services teams interacting with this repo much, but the Platform team needs to be in. Perhaps the code is more similar to the `gradle/plugins/src/main/kotlin/com.hedera.gradle.platform-publish.gradle.kts` file?

2024-07-23 16:43 UTC, mxtartaglia-sl commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.services.gradle.kts
> +group = "com.hedera.cryptography"
Still I think that we would need a different one for publishing 'native-support'
as @nathanklick suggested

2024-07-23 16:46 UTC, rbarker-dev commented on .github/CODEOWNERS
> +###################################
Sure thing; I'll get that added in

2024-07-23 18:04 UTC, rbarker-dev commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.services.gradle.kts
> +group = "com.hedera.cryptography"
moving to native-support breaks things based on the `native` keyword in java. I recommend leaving it as `nativesupport`

2024-07-23 18:14 UTC, rbarker-dev commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.services-publish.gradle.kts
> +                    organizationUrl = "https://www.hedera.com"
I moved the module dependencies to use com.hedera.gradle.platform-publish.gradle.kts

2024-07-23 18:14 UTC, rbarker-dev commented on hedera-cryptography-altbn128/build.gradle.kts
> +    id("com.hedera.gradle.services")
Swapped these over to platform.

2024-07-23 18:25 UTC, mxtartaglia-sl commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.services.gradle.kts
> +group = "com.hedera.cryptography"
Sorry @rbarkerSL, I was referring to my previous comment.
I meant that for the lib using this plugin (wrote `native-support` but should have been `hedera-nativesupport`) , @nathanklick  suggested usign the group:`com.hedera.commons`

2024-07-23 18:29 UTC, mxtartaglia-sl approved these changes

2024-07-23 18:34 UTC, nathanklick commented on .github/CODEOWNERS
> +/hedera-common-nativesupport/                          @hashgraph/platform-hashgraph @hashgraph/platform-base
nit: Spacing appears to differ here, but could be a GH UI issue.

2024-07-23 18:34 UTC, nathanklick commented on .github/dependabot.yml
> +    open-pull-requests-limit: 10
I don't believe this is required since I believe dependabot scans for all gradle projects under the specified path of `/` in the prior configuration.

2024-07-23 18:34 UTC, nathanklick commented on .github/workflows/build.yml
> +      - develop
```suggestion
```

2024-07-23 18:34 UTC, nathanklick commented on .github/workflows/build.yml
> +      - develop
```suggestion
```

2024-07-23 18:35 UTC, rbarker-dev commented on .github/CODEOWNERS
> +/hedera-common-nativesupport/                          @hashgraph/platform-hashgraph @hashgraph/platform-base
It's not; added `-common` to the module but forgot to remove the equivalent whitespace.

2024-07-23 18:51 UTC, mxtartaglia-sl commented
Are we using main for this repo instead of develop?

2024-07-23 18:53 UTC, rbarker-dev commented
> Are we using main for this repo instead of develop?

Yes.

2024-07-23 19:28 UTC, mxtartaglia-sl approved these changes

2024-07-23 21:13 UTC, mxtartaglia-sl commented
@rbarkerSL when I add the module-info in hedera-common-nativesupport
```
/**
 * Provides a set of generic functions loading native libraries in different system architectures when packaged
 * in a jar using a predefined organization, so they can be accessed with JNI.
 */
module com.hedera.common.nativesupport {
    exports com.hedera.common.nativesupport;

    requires static transitive com.github.spotbugs.annotations;
}

```
I receive the following error:
```
Could not determine the dependencies of task ':hedera-common-nativesupport:compileJava'.
> Could not resolve all dependencies for configuration ':hedera-common-nativesupport:compileClasspath'.
   > Could not find com.github.spotbugs:spotbugs-annotations:.
     Required by:
         project :hedera-common-nativesupport

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

https://github.com/hashgraph/hedera-cryptography#:~:text=14136_native_support

2024-07-24 06:41 UTC, jjohannes commented
@mxtartaglia-sl The problem with `Could not find com.github.spotbugs:spotbugs-annotations:.` is that you do not have a version defined for it. The generic Gradle error message is super unhelpful if you don't know that. the idication is the `:.` in the end (no version after the `:`).

You need to add the version here. Same as we do it in `hedera-services`:
[hedera-dependency-versions/build.gradle.kts](https://github.com/hashgraph/hedera-cryptography/blob/12-add-initial-ci-pipeline-and-gradle-implementations/hedera-dependency-versions/build.gradle.kts)

As example, I added the version for `spotbugs-annotations` in this PR.

```
    api("com.github.spotbugs:spotbugs-annotations:4.7.3") {
        because("com.github.spotbugs.annotations")
    }
```

2024-07-24 06:53 UTC, jjohannes commented
@mxtartaglia-sl @rbarkerSL @nathanklick after reading through the reviews, I pushed an update to this PR:

- I removed the part from the Gradle configs that have nothing to do with this repo. I realized that it's super confusing to those who miss context if we have them here just to remove them in the next step.
- Now that we actually have multiple "groups", it already starts to get confusing when setting them sometimes in plugins, sometimes in `build.gradle.kts`. Therefore, I changed the setup so that all the `group`s for the Modules are now defined in `settings.gradle.kts`. This moves them out of the plugins and makes the plugins more general reusable across repositories/products (already having in mind https://github.com/hashgraph/hedera-services/issues/14255). I want to do the same in _hedera-services_ - for more context, how and why we can do this now: https://github.com/hashgraph/hedera-services/pull/14245

The whole definition now looks like this

```
javaModules {
    directory("common") {
        group ="com.hedera.common"
    }
    directory("cryptography") {
        group = "com.hedera.cryptography"
    }
    versions("hedera-dependency-versions")
}
```

In this setup the `module-info.java` files are discovered and you do not need to list all the modules individually. For that, I moved the modules into a subfolder according to their "group". It feels natural to have all modules that belong to one "group" also grouped in one subfolder. Maybe a pattern we should eventually use in all repos (_hedera-services_ kind of has this structure already).

```
├── common
│   └── hedera-common-nativesupport
├── cryptography
│   ├── hedera-cryptography-altbn128
│   ├── hedera-cryptography-pairings-api
│   └── hedera-cryptography-pairings-signatures

```

Let me know if you agree. If not, I can revert/change that.

2024-07-24 07:10 UTC, jjohannes approved these changes

2024-07-24 14:03 UTC, mxtartaglia-sl approved these changes
Thanks @jjohannes and @rbarkerSL!
Sorry, I did not check if the versions were available; I assumed the version file was the same as in `hedera-services.`

The changes look good. This is really good, and I see that there is a path to a final version without repeated steps (like defining a library version in all repositories) or different structures per repository in which one has to remember specific rules; we can keep building on top of this base stone.
Thanks for completing this.

2024-07-24 14:15 UTC, nathanklick requested changes

2024-07-24 14:15 UTC, nathanklick commented on .github/workflows/build.yml
> +        run: ./gradlew releaseMavenCentralSnapshot -PpublishingPackageGroup=com.hedera --scan -PpublishSigningEnabled=true --no-configuration-cache
We should not be publishing to Maven Central on every pull request and commit against those PRs. This will get us rate limited very quickly and will impact our ability to push critical code from our self-hosted runners.

Publishing to Maven Central should be done sparingly (eg: only on merge to the `main` branch).

2024-07-24 14:15 UTC, nathanklick commented on .github/workflows/build.yml
> +        run: ./gradlew :reports:testCodeCoverageReport --scan --continue
This does not guarantee the unit tests will be executed. This only runs the JaCoCo code coverage aggregation.

2024-07-24 14:16 UTC, nathanklick requested changes

2024-07-24 14:16 UTC, nathanklick commented on .github/workflows/build.yml
This workflow should also use a unit test reporting plugin like `step-security/publish-unit-test-result-action`.

2024-07-24 14:20 UTC, nathanklick commented on gradle/plugins/src/main/kotlin/com/hedera/gradle/spotless/StripOldLicenseFormatterStep.kt
Probably not needed here since this is all new code.

2024-07-24 14:51 UTC, jjohannes commented on .github/workflows/build.yml
> +        run: ./gradlew :reports:testCodeCoverageReport --scan --continue
In the setup we have now it does. There is a hard dependency from the report generation tasks to the test tasks via the dependency from the report aggregation project to all test-report-producing projects. 
This changed when we introduced the single report aggregation project/task.

But for clarity, it would not hurt to add "test" as additional argument.

2024-07-24 15:04 UTC, jjohannes commented
@mxtartaglia-sl Centralizing third party versions across multiple repos is another topic to discuss in the future. After we unified Gradle setup unification (https://github.com/hashgraph/hedera-services/issues/14255) I would say.

There is the option to publish what we have in `heder-services/hedera-dependency-versions` as a BOM (metadata file with versions). Similar to: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/3.3.2/
And then use that across multiple repos.

But in this area, I feel like accepting duplication and relying on Dependabot to keep things on the latest versions everywhere is also an option.

I think the experience you gain when working with the setup as it is now will be helpful to discuss options in a few weeks.

2024-07-24 15:37 UTC, rbarker-dev commented on gradle/plugins/src/main/kotlin/com/hedera/gradle/spotless/StripOldLicenseFormatterStep.kt
Removed

2024-07-24 15:37 UTC, rbarker-dev commented on .github/workflows/build.yml
Added, probably needs some additional configuration

2024-07-24 15:37 UTC, rbarker-dev commented on .github/workflows/build.yml
> +        run: ./gradlew :reports:testCodeCoverageReport --scan --continue
Added the test argument

2024-07-24 15:37 UTC, rbarker-dev commented on .github/workflows/build.yml
> +        run: ./gradlew releaseMavenCentralSnapshot -PpublishingPackageGroup=com.hedera --scan -PpublishSigningEnabled=true --no-configuration-cache
Added a check to ensure that the ref is `main`

2024-07-24 16:23 UTC, nathanklick requested changes

2024-07-24 16:23 UTC, nathanklick commented on .github/workflows/build.yml
> +        run: ./gradlew releaseMavenCentralSnapshot -PpublishingPackageGroup=com.hedera --scan -PpublishSigningEnabled=true --no-configuration-cache
```suggestion
        run: ./gradlew releaseMavenCentralSnapshot -PpublishingPackageGroup=com.hedera.cryptography --scan -PpublishSigningEnabled=true --no-configuration-cache
```

2024-07-24 18:51 UTC, jjohannes commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.hedera-cryptography-publish.gradle.kts
> +
I don't think this split up is necessary. The publishing credentials are bound to "com.hedera" IIUC and not the "subgroups". In hedera-services we also have this and publish on on go: 'con.hedera.hashgraph' and 'con.hedera.evm'.

2024-07-24 19:18 UTC, rbarker-dev commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.hedera-cryptography-publish.gradle.kts
> +
The request was to distinguish the two in order to future proof a little bit. There is a path where we pull nativesupport into its own repository. This will simplify doing that.

2024-07-24 19:19 UTC, nathanklick approved these changes

2024-07-24 19:19 UTC, merged

2025-01-14 17:51 UTC, swirlds-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/hedera-cryptography/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: