Change to CODEOWNERS
hiero-ledger/hiero-cryptography pull request #28
Opened 2024-07-25 14:43 UTC by mxtartaglia-sl

**Related issue(s)**:

Fixes #14403

Proposal this work is based on:[ platform-sdk/docs/proposals/TSS-Library/TSS-Library.md](https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/proposals/TSS-Library/TSS-Library.md)

2024-07-25 15:27 UTC, nathanklick requested changes

2024-07-25 15:27 UTC, nathanklick commented on .github/CODEOWNERS
> +/hedera-bls-rust-jni                                    @hashgraph/platform-hashgraph @hashgraph/platform-data @hashgraph/platform-base @hashgraph/platform-architects
Aren't these deprecated and should be removed?

2024-07-25 15:27 UTC, nathanklick commented on .github/CODEOWNERS
> +/common/hedera-common-nativesupport/                    @hashgraph/platform-hashgraph @hashgraph/platform-data @hashgraph/platform-base @hashgraph/platform-architects
This may create a lot of noise for all 4 teams and this also means any one of these team members can approve a PR for merge. This should be limited to only the team(s) which hold the primary responsibility for this code.

2024-07-25 15:27 UTC, nathanklick commented on .github/CODEOWNERS
> +/cryptography/hedera-cryptography-pairings-signatures/  @hashgraph/platform-hashgraph @hashgraph/platform-data @hashgraph/platform-base @hashgraph/platform-architects
Since these are identical it can be simplified to a single rule.

```suggestion
/cryptography/         @hashgraph/platform-hashgraph @hashgraph/platform-data @hashgraph/platform-base @hashgraph/platform-architects
```

2024-07-25 15:28 UTC, mxtartaglia-sl commented on .github/CODEOWNERS
> +/hedera-bls-rust-jni                                    @hashgraph/platform-hashgraph @hashgraph/platform-data @hashgraph/platform-base @hashgraph/platform-architects
Yes, adding them to be able to remove them from inside the team

2024-07-25 15:30 UTC, mxtartaglia-sl commented on .github/CODEOWNERS
> +/common/hedera-common-nativesupport/                    @hashgraph/platform-hashgraph @hashgraph/platform-data @hashgraph/platform-base @hashgraph/platform-architects
Well, those "teams" don't exist anymore. Any of the members of those groups can modify this code.

2024-07-25 15:31 UTC, mxtartaglia-sl commented on .github/CODEOWNERS
> +/cryptography/hedera-cryptography-pairings-signatures/  @hashgraph/platform-hashgraph @hashgraph/platform-data @hashgraph/platform-base @hashgraph/platform-architects
thanks! I wasn't sure if it was going to work!

2024-07-25 19:34 UTC, nathanklick approved these changes

2024-07-25 19:34 UTC, merged

2025-01-14 17:51 UTC, swirlds-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/hedera-cryptography/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: