feat: 13359 ECKeyGen
hiero-ledger/hiero-cryptography pull request #36
Opened 2024-08-06 20:23 UTC by mxtartaglia-sl

**Description:**
A tool similar to ssh-keygen that allows the creation of EC Private / Public key pairs.
**Note for reviewers(s):**
Compiled artifacts are provided temporally. They will be removed after CI/CD support for compiling rust code is available.

**Related issue(s):**

Fixes https://github.com/hashgraph/hedera-services/issues/13359

**Proposal this work is based on:**[ platform-sdk/docs/proposals/TSS-Library/TSS-Library.md](https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/proposals/TSS-Library/TSS-Library.md)

2024-08-07 16:26 UTC, kfa-aguda commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/KeyGen.java
> +        if (args.length == 0 || args[0].equals("--help")) {
I suggest collecting the args into well named "command name", "private key path", "public key path" etc. for readability.

2024-08-07 16:26 UTC, kfa-aguda commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/PemFiles.java
> +     * @param keyType eiter "PUBLIC KEY" or "PRIVATE KEY" string
```suggestion
     * @param keyType either "PUBLIC KEY" or "PRIVATE KEY" string
```

2024-08-07 16:26 UTC, kfa-aguda commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/PemFiles.java
> +        String header = "-----BEGIN " + keyType + "-----";
is it worth validating the keyType is of the exact values required as per javadoc? I see you're passing the correct values from main but I think it's worth validating here too.

2024-08-07 16:26 UTC, kfa-aguda commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/PemFiles.java
> +        String header = "-----BEGIN " + Objects.requireNonNull(keyType, "keyType must not be null") + "-----\n";
same comment above applies.

2024-08-07 18:05 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/PemFiles.java
> +        String header = "-----BEGIN " + keyType + "-----";
Yes, agreed, will add an enum so there is no way to introduce an invalid value in the parameter.

2024-08-07 18:05 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/KeyGen.java
> +        if (args.length == 0 || args[0].equals("--help")) {
Makes sense

2024-08-12 15:53 UTC, edward-swirldslabs commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/KeyGenerator.java
> +    int generateKeyPair(final int groupAssignment, byte[][] out);
The `out` parameter is very confusing to me.  My best guess is that the input 2D array is only partially initialized, and it is expected to be a length of 2?  But the second subscript on each is uninitialized and or set to null and the method will set those values for a return?  

I'm curious why the return value couldn't be byte[][], and have it set to null if there is an error.     It's a lot cleaner and clearer if there is 1 source of responsibility for instantiating the 2D array.  The alternative is to create a class to hold the pair.

2024-08-12 15:53 UTC, edward-swirldslabs commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/KeyGenerator.java
> +     * @return An array representing the public key
you have an integer status returned above.  Is it possible for this operation to fail as well?  is null possible as a return value to indicate a failure?   since `byte[]` can be null, we need to annotated the return value with a nullity marking.

2024-08-12 15:53 UTC, edward-swirldslabs commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/NativeKeyGenerator.java
> +        if (IS_INITIALIZED.compareAndSet(false, true)) {
Thread A and Thread B hit line 40 at the same time.  Thread A sets the new value successfully and enters the body of the if block and does the work of initializing.    Thread B wakes up, sees the value is already true, skips the block and immediately returns.   Thread B returns before Thread A is done with initialization.  This looks like a race condition. 

I think the initialization has to be done while thread A is holding onto the lock.

2024-08-12 15:53 UTC, edward-swirldslabs commented on cryptography/hedera-cryptography-eckeygen/src/test/java/com/hedera/cryptography/eckeygen/KeysGenerationServiceTest.java
> +class KeysGenerationServiceTest {
Is it possible to test any of the key functionality such as signing and encrypting?  Or not yet?

2024-08-12 15:56 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/test/java/com/hedera/cryptography/eckeygen/KeysGenerationServiceTest.java
> +class KeysGenerationServiceTest {
Not yet; the scope here was to generate the key files. The operations for signing and encrypting will be generated in future tasks and in the 'pairings-signatures-library'.

2024-08-12 16:15 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/KeyGenerator.java
> +     * @return An array representing the public key
> since byte[] can be null, we need to annotated the return value with a nullity marking.

I can't annotate. This would produce many complications when compiling the header file, as it would require all the necessary libraries to be in the classpath.

But i can do a better job in the javadocs

2024-08-12 16:15 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/KeyGenerator.java
> +    int generateKeyPair(final int groupAssignment, byte[][] out);
> My best guess is that the input 2D array is only partially initialized, and it is expected to be a length of 2? But the second subscript on each is uninitialized and/or set to null, and will the me set those values for a return?

 Correct!

> It's a lot cleaner and clearer if there is 1 source of responsibility for instantiating the 2D array

I agree. I wouldn't say I like this, but this approach facilitates the JNI operations. Returning Java types in JNI methods creates a coupling between Rust and Java in the form of strings. We need to qualify type names fully, and in case something changes, we have to maintain that parity. I want to reduce that coupling. Furthermore, returning a Java matrix in Rust requires too much boilerplate Rust code, which I am saving by sending the outmost array as an input parameter.

I'll review this to see if i can circumvent this, or restate the javadocs to be clearer

2024-08-12 16:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/NativeKeyGenerator.java
> +        if (IS_INITIALIZED.compareAndSet(false, true)) {
Although no multithreading is expected here, I will fix this issue as it can become a template for further solutions.
I don't want to pay the cost for a synchronized method in all calls that will mostly be:
'if (false){} return;'

2024-08-12 18:21 UTC, rbarker-dev requested changes

2024-08-12 18:21 UTC, rbarker-dev commented on cryptography/hedera-cryptography-eckeygen/Cargo.toml
> +rand = "*"
Let's throw a newline at the end here

2024-08-12 18:21 UTC, rbarker-dev commented on cryptography/hedera-cryptography-eckeygen/src/main/resources/software/darwin/arm64/libkey_gen.dylib
Why are we committing binary files?

2024-08-12 18:21 UTC, rbarker-dev commented on cryptography/hedera-cryptography-eckeygen/src/main/resources/software/linux/amd64/libkey_gen.so
Why are we committing binary files?

2024-08-12 18:39 UTC, rbarker-dev commented on cryptography/hedera-cryptography-eckeygen/src/main/resources/software/darwin/arm64/libkey_gen.dylib
until we have support for compiling Rust, need to push them so that the tests can execute and the code works.

2024-08-12 18:49 UTC, rbarker-dev submitted a review, later dismissed

2024-08-12 21:20 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/KeyGenerator.java
> +    int generateKeyPair(final int groupAssignment, byte[][] out);
Ok, I returned the byte[][] from rust code. 
It required more bureaucratic code from the Rust side, plus handling of lifespans for the returning variable, but it ended up with a more consistent approach between the two methods.
Indeed, the java side got clearer and cleaner.

2024-08-12 21:23 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/KeyGenerator.java
> +     * @return An array representing the public key
I introduced the annotations; the effect is that it is more difficult to compile the headers from the current version. But I should not require them to be compiled so often. Besides, it is an optional step; what matters is the implementation.
In any case, if needed, I can create a new class using only the native methods to generate the new headers and then throw out the new class.

2024-08-12 21:23 UTC, mxtartaglia-sl commented on cryptography/hedera-cryptography-eckeygen/src/main/java/com/hedera/cryptography/eckeygen/NativeKeyGenerator.java
> +        if (IS_INITIALIZED.compareAndSet(false, true)) {
Let me know what you think about the new approach.

2024-08-13 15:30 UTC, edward-swirldslabs approved these changes
LGTM

2024-08-14 15:06 UTC, rbarker-dev approved these changes

2024-08-14 15:08 UTC, merged

2025-01-14 17:51 UTC, swirlds-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/hedera-cryptography/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: