build: rust compilation support
hiero-ledger/hiero-cryptography pull request #70
Opened 2024-09-19 13:02 UTC by jjohannes

**Description**:
Integrate Gradle and Rust/Cargo:

- [x] Gradle tasks for Rust compilation
- [x] Install Rust toolchain via GitHub Actions
- [x] Build the `linux-x86-64` target
- [x] Enhance Rust toolchain setup to support cross-compilation for all desired targets
   - Windows cross-compilation using `lld` based on https://jake-shadle.github.io/xwin/ 

**Related issue(s)**:

https://github.com/hashgraph/hedera-services/issues/14100

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-09-20 22:08 UTC, mxtartaglia-sl submitted a review, later dismissed
This is great, Jendrik! With this implementation, I can stop uploading the binaries for unit test to pass.
The only comment I would make is that maybe it is worth having the targets in some sort of enum, but I didn't investigate whether that is possible.

2024-10-07 14:12 UTC, mxtartaglia-sl approved these changes

2024-10-07 15:52 UTC, mxtartaglia-sl submitted a review, later dismissed

2024-10-08 19:11 UTC, edward-swirldslabs submitted a review, later dismissed

2024-10-15 12:35 UTC, mxtartaglia-sl submitted a review, later dismissed

2024-10-15 15:34 UTC, jjohannes commented
Once this is in, we could extend the pipeline to run all tests on runners with different operating systems. The built libraries are pulled from the Gradle cache. I have already tested that on a branch (#82) and [it works](https://github.com/hashgraph/hedera-cryptography/actions/runs/11368312816?pr=82). 

Discovered this issue: https://github.com/hashgraph/hedera-cryptography/issues/81

Prepared follow up PR (for once this is merged): #82

2024-10-15 17:16 UTC, rbarker-dev approved these changes

2024-10-15 17:16 UTC, rbarker-dev commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.feature.rust.gradle.kts
> +// Cargo might do installation work, do not run in parallel:
why not run in parallel?

2024-10-15 17:35 UTC, rbarker-dev requested changes

2024-10-15 17:35 UTC, rbarker-dev commented on README.md
To get `./gradlew build` to succeed I also needed to execute the following command: `rustup target add x86_64-pc-windows-msvc`

2024-10-15 17:35 UTC, rbarker-dev commented on README.md
I think we should put that in as a requirement for building on mac.

2024-10-16 07:09 UTC, jjohannes commented on README.md
Good catch! Added it to the Readme.

2024-10-16 08:17 UTC, jjohannes commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.feature.rust.gradle.kts
> +// Cargo might do installation work, do not run in parallel:
Cargo/rust is doing installation/preparation work before compiling our code. If we run this in parallel, we start `cargo` multiple times in parallel. It then tries to do the same things multiple times in parallel and fails with files access issues (it's apparently not designed to run in parallel).
I tried to isolate this into [a share build service](https://docs.gradle.org/current/userguide/build_services.html), but did not succeed as this is triggered automatically when you start the (cross) compilation through cargo. We would somehow need to make sure that everything is prepared before the actual compilation starts. But I did not get it working (maybe cargo does support that at all).

2024-10-16 15:16 UTC, rbarker-dev approved these changes
LGTM

2024-10-16 16:01 UTC, mxtartaglia-sl approved these changes

2024-10-16 16:01 UTC, mxtartaglia-sl commented
Tested locally and working. Both in Linux and in mac.

2024-10-16 16:51 UTC, merged

2025-01-14 17:50 UTC, swirlds-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/hedera-cryptography/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: