Run hedera-cryptography-altbn128 tests on multiple operating systems
hiero-ledger/hiero-cryptography pull request #82
Opened 2024-10-16 14:57 UTC by jjohannes

**Description**:

- Follow up to #70 
- Affected by #81

2024-10-16 15:31 UTC, jjohannes commented
The CI build sometimes runs into this problem with `xwin`: https://github.com/Jake-Shadle/xwin/issues/141

If it fails, trigger a re-run. I hope there will be a fix or stable workaround soon.

2024-10-16 20:40 UTC, rbarker-dev requested changes

2024-10-16 20:40 UTC, rbarker-dev commented on gradle/plugins/src/main/kotlin/com/hedera/gradle/tasks/CargoBuildTask.kt
> +            val crossCompiler = if (buildsForWindows) "xwin@0.6.6-rc.1" else "cargo-zigbuild"
Can you add a comment linking to the thread where it was determined we needed to use 0.6.6-rc.1 here in the code? That way if a more stable version is released it should be a little easier to justify switching to it.

2024-10-17 14:28 UTC, jjohannes commented on gradle/plugins/src/main/kotlin/com/hedera/gradle/tasks/CargoBuildTask.kt
> +            val crossCompiler = if (buildsForWindows) "xwin@0.6.6-rc.1" else "cargo-zigbuild"
:+1: Comment added. I am following the _xwin_ issue and will keep an eye on this to remove it again once it is no longer needed.

2024-10-17 14:58 UTC, jjohannes commented on common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java
> +        final String fileName = Path.of(libName).getFileName().toString();
@timo0 now that the tests are running on Windows, I found this other special case: On Windows, the DLL extension is part of the library name to load.

On the upside, with this change the tests pass on Windows. Which is a good sign that the cross-compilation is successful. 🎉

2024-10-17 15:08 UTC, mxtartaglia-sl commented on common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java
> +        final String fileName = Path.of(libName).getFileName().toString();
thanks @jjohannes

2024-10-17 15:08 UTC, mxtartaglia-sl submitted a review, later dismissed

2024-10-17 15:22 UTC, jjohannes commented on .github/workflows/build.yml
> +          files: "**/build/test-results/test/TEST-*.xml"
Not related directly, but the path here was wrong and thus test results were not published to PRs.

2024-10-17 15:31 UTC, mxtartaglia-sl approved these changes

2024-10-17 16:36 UTC, mxtartaglia-sl commented on .github/workflows/build.yml
> +          files: "**/build/test-results/test/TEST-*.xml"
thanks!

2024-10-17 19:44 UTC, rbarker-dev approved these changes
LGTM

2024-10-18 04:33 UTC, merged

2025-01-14 17:49 UTC, swirlds-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/hedera-cryptography/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: