fix: enable mac compile on local builds
hiero-ledger/hiero-cryptography pull request #96
Opened 2024-10-24 16:29 UTC by mxtartaglia-sl

**Description**:
Re enables mac compile on mac desktops

**Note(s) for reviewer**:
Sorry I did not get it right the first time

2024-10-24 16:46 UTC, rbarker-dev approved these changes

2024-10-24 16:47 UTC, rbarker-dev submitted a review, later dismissed

2024-10-24 16:47 UTC, rbarker-dev commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.feature.rust.gradle.kts
> +// temporarily disable mac compilation ON THE PIPELINE because it's failing on GitHub actions
```suggestion

```

2024-10-24 16:51 UTC, mxtartaglia-sl commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.feature.rust.gradle.kts
> +// temporarily disable mac compilation ON THE PIPELINE because it's failing on GitHub actions
Do you mean to remove the comment?
It is there to keep track that it would need to be resolved eventually.
Either way, committed your suggestion but lmk

2024-10-24 17:05 UTC, nathanklick requested changes

2024-10-24 17:05 UTC, nathanklick commented on gradle/plugins/src/main/kotlin/com.hedera.gradle.feature.rust.gradle.kts
CI should build for MacOS X as well. CI will be what produces the final shipping artifact.

2024-10-24 17:09 UTC, nathanklick submitted a review, later dismissed

2024-10-24 17:24 UTC, nathanklick approved these changes

2024-10-24 19:06 UTC, merged

2025-01-14 17:49 UTC, swirlds-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/hashgraph/hedera-cryptography/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: